[package]
name = "webrtc-sys"
version = "0.3.2"
edition = "2021"
homepage = "https://livekit.io"
license = "Apache-2.0"
description = "Unsafe bindings to libwebrtc"
repository = "https://github.com/livekit/client-sdk-rust"

[features]
default = []
static = []

[dependencies]
log = "0.4"

[build-dependencies]
libwebrtc-build = { version="0.3.2", path="./libwebrtc/build-utils"}

[dev-dependencies]
env_logger = "0.10"
