[package]
name = "data_streams"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full", "parking_lot"] }
futures = "0.3"
parking_lot = { version = "0.12.1", features = ["deadlock_detection"] }
env_logger = "0.10"
livekit = { path = "../../livekit", features = ["native-tls"] }
livekit-api = { path = "../../livekit-api" }
log = "0.4"
