[package]
name = "libwebrtc-build"
version = "0.3.2"
edition = "2021"
license = "Apache-2.0"
description = "Build utilities when working with libwebrtc"
repository = "https://github.com/livekit/rust-sdks"

[dependencies]
ureq = "2.9"
zip = "0.6"
scratch = "1.0"
fs2 = "0.4"
